version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: joan_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joan
      MYSQL_DATABASE: joan
      MYSQL_USER: joan
      MYSQL_PASSWORD: joan
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3010:3306"

  httpd:
    image: httpd:2.4.58
    container_name: joan_httpd
    restart: always
    volumes:
      - ./httpd:/usr/local/apache2/htdocs/
    ports:
      - "8010:80"

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joan_java
    restart: always
    depends_on:
      - mysql
      - artemis
    ports:
      - "9010:8080"
    environment:
      SPRING_ARTEMIS_BROKER_URL: tcp://artemis:61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin

  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      DISABLE_SECURITY: 'true'
    volumes:
      - artemis_data:/var/lib/artemis/data

volumes:
  mysql_data:
  artemis_data:
